### ISSUE TITLE
Model development

### ISSUE THREAD

**Issue by ebuhle** [ebuhle/LeatherbackNesting#1]
Hi @hoffmannsarahlouise, here's a quick synopsis to catch you up on the analysis thus far and what's next.

My initial thought was to treat each response variable as a multivariate time series, i.e., repeated observations for > 500 identified turtles, ignoring non-"encounters" for now. There are many ways to model such data, but I quickly realized we were constrained by the low probability of resighting individuals. The vast majority of turtles were seen in only 1 or 2 years, and the longest series is 7 years: 

```r
table(tapply(nest$year, nest$name, function(x) length(unique(x))))

  1   2   3   4   5   6   7 
321 141  68  21  14   1   1 
```

That rules out any class of models with correlated but unique "states" for each turtle. An alternative is dynamic factor analysis (DFA), which seeks to reduce a high-dimensional time series to a lower-dimensional set of factors or "common trends", but that's a nonstarter too given data sparsity. I ended up trying a model where the observations `y[j,t]` for turtle `j` in year `t` arise from a single "common trend" modeled as a random walk `alpha[t]` with drift `mu`, plus independent random turtle effects `theta[j]`, plus residual error `epsilon[j,t]`:

```
j[j,t] = alpha[t] + theta[j] + epsilon[j,t]
alpha[t] = alpha[t-1] + mu + omega[t], omega[t] ~ N(0, sigma_alpha)
theta[j] ~ N(0, sigma_theta)
epsilon[j,t] ~ N(0, sigma)
```

Covariates could enter via the common trend and/or an effect on each individual observation, but I didn't make it that far. Just the basic formulation above produced rather sad results when fitted to encounter DOY and max CCL. For example, here's DOY:

```
Inference for Stan model: HRWSS.
3 chains, each with iter=2000; warmup=1000; thin=1; 
post-warmup draws per chain=1000, total post-warmup draws=3000.

                mean se_mean    sd     2.5%      50%    97.5% n_eff Rhat
mu             -0.39    0.03  1.13    -2.84    -0.35     1.80  1158 1.00
sigma_alpha     3.77    0.07  1.69     1.24     3.52     7.99   603 1.01
sigma_theta     7.29    0.03  0.93     5.48     7.30     9.10   732 1.00
sigma          21.52    0.01  0.43    20.71    21.51    22.39  1578 1.00
alpha[1]      134.85    0.05  1.87   131.17   134.87   138.46  1495 1.00
alpha[2]      130.06    0.04  1.98   125.88   130.10   133.64  2538 1.00
alpha[3]      129.99    0.02  1.36   127.25   130.00   132.68  3216 1.00
alpha[4]      129.37    0.03  1.45   126.68   129.32   132.27  2906 1.00
alpha[5]      126.82    0.03  1.51   123.83   126.86   129.71  1998 1.00
alpha[6]      130.10    0.03  1.44   127.39   130.08   132.99  2358 1.00
alpha[7]      129.06    0.03  1.94   125.15   129.06   132.86  3943 1.00
alpha[8]      130.39    0.05  2.78   125.34   130.20   136.33  3341 1.00
alpha[9]      130.12    0.05  2.72   125.19   129.99   136.00  2572 1.00
alpha[10]     126.29    0.06  2.38   121.44   126.48   130.55  1515 1.00
alpha[11]     129.63    0.04  2.33   125.02   129.60   134.44  3098 1.00
alpha[12]     131.06    0.04  1.80   127.75   130.97   134.78  2573 1.00
alpha[13]     128.89    0.03  1.84   125.09   128.98   132.42  3636 1.00
alpha[14]     129.46    0.03  1.51   126.70   129.48   132.36  3486 1.00
lp__        -1098.00    1.06 25.66 -1147.92 -1098.22 -1045.56   588 1.00

Samples were drawn using NUTS(diag_e) at Wed Mar 10 11:12:54 2021.
For each parameter, n_eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor on split chains (at 
convergence, Rhat=1).
```

The credible interval for `mu` shows no indication of a systematic trend in encounter date common to all turtles, which is consistent with the series of annual `alpha[t]` estimates and the quick and dirty plots in [the script](https://github.com/ebuhle/LeatherbackNesting/blob/main/analysis/leatherback_nesting_analysis.R). CCL is similarly underwhelming, with a side of numerical problems (terrible mixing).

At this point I realized that the only thing differentiating this model from a standard hierarchical model with a linear year effect and IID random effects of both turtle *and* year is that the year effects here are represented as a random walk. Since there's little indication of a shared interannual signal that is distinguishable from the noise, at least for these two variables, a custom-built model seems like more trouble than it's worth. So my next move will be to try an off-the-shelf package (either **rstanarm** or **brms**) to fit hierarchical models that (maybe?) allow an AR(1) correlation structure for the observations themselves. I haven't fully reckoned with how to incorporate the nonlinear growth trajectories for CCL (i.e., the annual growth rate depends on initial size), but the two binomial outcomes (proportion neophytes and nest success) would be straightforward.

Hope that wasn't too cryptic or telegraphic. I'd love to hear any thoughts or suggestions. I did have two minor questions for you that came up during data processing:

- One turtle (ID 1587, encountered only once) has name "2-May". Is this an Excel error?
- One encounter (664, HAEDI) has date 1/5/1900 (removed from the analysis for now).

**Comment by hoffmannsarahlouise** [comment]
Thanks for the update- sounds like good progress!

1. Yes, I am assuming excel formatting error.
2. Another error- come on microsoft..

Let me know how else I might be able to help!

**Comment by ebuhle** [comment]
> 1. Yes, I am assuming excel formatting error.
> 2. Another error- come on microsoft..

OK, well (1) doesn't really affect anything, although I'm sad for that turtle with conspecifics named QUEENIE, RASTA, etc. I was worried that the date in the name column might indicate cells being shifted, but that doesn't appear to be the case, at least to the uninitiated (i.e., me). As for (2), tossing out that encounter unless / until we resolve the date is NBD.

I do have another question for you, though, @hoffmannsarahlouise. I think I understand the distinction between surveys and encounters (and as I said, the analysis so far only includes the latter). But there are five cases where an encounter and the corresponding survey occur not just on different dates (e.g., nighttime encounter followed by daytime survey) but in different years. Surely these are errors, or am I missing something?

```
nest %>% filter(year(date_encounter) != year(date_survey)) %>% select(name, year, date_encounter, encounter, date_survey, nest)

        name year date_encounter encounter date_survey            nest
1     AMANDA 2011     2011-04-11      1690  2014-06-01 DC-060114-1A-JB
2      DARIA 2012     2012-06-24      2428  2015-04-09 DC-040915-9A-JB
3    KATRINA 2011     2011-05-14      1856  2014-06-10            <NA>
4 PERSEPHONE 2011     2011-04-21      1742  2014-06-05 DC-060514-6a-JB
5    POLARIS 2011     2011-05-03      1790  2014-06-08 DC-060814-4a-JB
```

**Comment by hoffmannsarahlouise** [comment]
I am going to check with LMC about all of the date discrepancies. I could certainly hazard guesses but I don't think it would get us any closer to an answer!
